"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process");
const snap=require("../rehearsal/db-recovery/snapshot"),{assertPristineBootstrap}=require("../rehearsal/db-recovery/pristine-baseline"),{MutationGate}=require("../rehearsal/db-recovery/mutation-gate"),{classify}=require("../rehearsal/db-recovery/rpo"),{EXPECTED_POST_BACKUP_TABLES,buildDeltaLedger}=require("../rehearsal/db-recovery/delta-ledger"),{assertRestoreGateEvidence}=require("../rehearsal/db-recovery/phase-one"),{VALUES,proveMysql84JsonDumpRestoreStability}=require("./support/mysql84-json-stability");
const root=path.join(__dirname,".."); const phaseOneSource=fs.readFileSync(path.join(root,"rehearsal/db-recovery/phase-one.js"),"utf8"); const jsonProof=fs.readFileSync(path.join(root,"deploy/field-test/db-recovery-json-stability-proof"),"utf8"); const fieldTest=fs.readFileSync(path.join(root,"deploy/field-test/field-test"),"utf8"); const watchdog=path.join(root,"deploy/field-test/db-unpause-watchdog"); const host=fs.readFileSync(path.join(root,"deploy/field-test/db-recovery-host"),"utf8"); const runner=fs.readFileSync(path.join(root,"rehearsal/db-recovery-continuity.js"),"utf8");
test("fixed current schema contract is exactly 19 base tables with supported types and complete PKs",()=>{assert.equal(Object.keys(snap.contract).length,19);for(const [t,s] of Object.entries(snap.contract)){assert.ok(s.columns.length,t);assert.ok(s.primaryKey.length,t);for(const c of s.columns)assert.match(c.type,snap.ALLOWED_TYPES);}});
test("schema drift and changed primary keys fail closed",()=>{const rows=[];for(const [t,s] of Object.entries(snap.contract))s.columns.forEach((c,i)=>rows.push({TABLE_NAME:t,COLUMN_NAME:c.name,COLUMN_TYPE:c.type,IS_NULLABLE:c.nullable?"YES":"NO",PK_ORDINAL:s.primaryKey.indexOf(c.name)<0?null:s.primaryKey.indexOf(c.name)+1}));assert.doesNotThrow(()=>snap.validateSchema(rows));rows[0].COLUMN_TYPE="varchar(999)";assert.throws(()=>snap.validateSchema(rows),/drift/);});
test("canonical cells are server HEX and never JavaScript Number",()=>{const q=snap.rowQuery("matches",snap.contract.matches);assert.match(q,/HEX\(CAST/);assert.doesNotMatch(q,/parseInt|parseFloat|Number\(/);});
test("timestamps use UTC and retain TIMESTAMP(6)/DATETIME(6) contract",()=>{assert.ok(snap.contract.match_schedules.columns.some(c=>c.type==="datetime(6)"));assert.ok(snap.contract.court_operating_conditions.columns.some(c=>c.type==="timestamp(6)"));assert.match(snap.snapshot.toString(),/SET time_zone = '\+00:00'/);});
test("snapshot orders by complete declared primary key",()=>{assert.match(snap.rowQuery("player_partners",snap.contract.player_partners),/ORDER BY `player_id`,`partner_id`,`tournament_id`$/);});
test("snapshot accepts current camelCase and snake_case identifiers but rejects unsafe syntax",()=>{const players=snap.rowQuery("players",snap.contract.players);assert.match(players,/`curP`/);assert.match(players,/`lastR`/);assert.match(snap.rowQuery("safe_table",{columns:[{name:"snake_case"}],primaryKey:["snake_case"]}),/`snake_case`/);for(const name of ["a-b","a.b","`a`","a b","a;b","1abc"])assert.throws(()=>snap.rowQuery(name,{columns:[{name:"id"}],primaryKey:["id"]}),/unsafe schema identifier/);});
test("watchdog rejects zero, extra, and malformed arguments",()=>{for(const args of [[],["a".repeat(64),"extra"],["A".repeat(64)]])assert.notEqual(cp.spawnSync(watchdog,args,{encoding:"utf8"}).status,0);});
test("watchdog has fixed 45 second deadline and only exact unpause Docker action",()=>{const s=fs.readFileSync(watchdog,"utf8");assert.match(s,/deadline_seconds=45/);assert.match(s,/direct\) docker_unpause\(\) \{ docker unpause "\$container_id";/);assert.match(s,/sudo-n\) docker_unpause\(\) \{ sudo -n docker unpause "\$container_id";/);assert.doesNotMatch(s,/docker (ps|inspect|pause|stop|rm|system)/);assert.doesNotMatch(s,/eval|command string/);});
test("watchdog TERM disarms without Docker",async()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"wd-")),fake=path.join(tmp,"docker");fs.writeFileSync(fake,"#!/bin/sh\nexit 99\n",{mode:0o755});const p=cp.spawn(watchdog,["a".repeat(64)],{env:{...process.env,TOP_DB_WATCHDOG_DOCKER_MODE:"direct",PATH:`${tmp}:${process.env.PATH}`}});let out="";p.stdout.on("data",x=>out+=x);await new Promise(r=>setTimeout(r,100));p.kill("SIGTERM");const code=await new Promise(r=>p.on("exit",r));assert.equal(code,0);assert.match(out,/"event":"disarmed"/);});
function runDeadline(mode) { const tmp=fs.mkdtempSync(path.join(os.tmpdir(),`wd-${mode}-`)),script=path.join(tmp,"watchdog"),calls=path.join(tmp,"calls");fs.writeFileSync(script,fs.readFileSync(watchdog,"utf8").replace("deadline_seconds=45","deadline_seconds=0"),{mode:0o755});fs.writeFileSync(path.join(tmp,"docker"),`#!/bin/sh\nprintf 'docker:%s\\n' "$*" >>"$WATCHDOG_CALLS"\n`,{mode:0o755});fs.writeFileSync(path.join(tmp,"sudo"),`#!/bin/sh\nprintf 'sudo:%s\\n' "$*" >>"$WATCHDOG_CALLS"\n`,{mode:0o755});const id="b".repeat(64),result=cp.spawnSync(script,[id],{encoding:"utf8",env:{...process.env,TOP_DB_WATCHDOG_DOCKER_MODE:mode,WATCHDOG_CALLS:calls,PATH:`${tmp}:${process.env.PATH}`}});assert.equal(result.status,0,result.stderr);return {id,calls:fs.readFileSync(calls,"utf8"),output:result.stdout};}
test("watchdog deadline uses selected direct Docker mode",()=>{const r=runDeadline("direct");assert.equal(r.calls,`docker:unpause ${r.id}\n`);assert.match(r.output,/"dockerAccessMode":"direct"/);});
test("watchdog deadline uses sudo -n when direct Docker is unavailable",()=>{const r=runDeadline("sudo-n");assert.equal(r.calls,`sudo:-n docker unpause ${r.id}\n`);assert.match(r.output,/"dockerAccessMode":"sudo-n"/);});
test("launcher selects and independently proves non-interactive sudo mode",()=>{assert.match(host,/sudo -n -k docker info/);assert.match(host,/setsid sudo -n -k docker info <\/dev\/null/);assert.match(host,/TOP_DB_WATCHDOG_DOCKER_MODE=\$docker_access_mode setsid nohup/);assert.doesNotMatch(host,/sudo docker/);});
test("watchdog proof creates a private parent but rejects an existing run ID",()=>{assert.match(host,/mkdir -p -- "\$parent"; chmod 0700 "\$parent"; mkdir -m 0700 -- "\$evidence"/);assert.match(host,/watchdog-proof-start[\s\S]*create_run_evidence_directory/);const root=fs.mkdtempSync(path.join(os.tmpdir(),"db-recovery-evidence-")),parent=path.join(root,"evidence","db-recovery"),run=path.join(parent,"wd-proof-001"),command=`mkdir -p -- "$1" && chmod 0700 "$1" && mkdir -m 0700 -- "$2"`;let result=cp.spawnSync("sh",["-c",command,"sh",parent,run]);assert.equal(result.status,0);assert.equal(fs.statSync(parent).mode&0o777,0o700);assert.equal(fs.statSync(run).mode&0o777,0o700);result=cp.spawnSync("sh",["-c",command,"sh",parent,run]);assert.notEqual(result.status,0);});
test("detached controller hard-deadline design survives foreground SIGKILL",()=>{assert.match(host,/setsid nohup/);assert.match(host,/kill -KILL \$\$/);assert.match(host,/deadline-result/);});
test("mutation gate admits OPEN writes and rejects CLOSED writes",async()=>{const g=new MutationGate();assert.equal(await g.mutate("x",async()=>7),7);await g.close();await assert.rejects(g.mutate("y",async()=>8),/CLOSED/);});
test("mutation gate drains in-flight writes",async()=>{const g=new MutationGate();let release;const pending=g.mutate("x",()=>new Promise(r=>release=r));const closing=g.close();assert.equal(g.state,"CLOSING");release(1);assert.equal((await closing).inFlightWrites,0);await pending;});
test("ambiguous mutation is rejected before binding",async()=>{const g=new MutationGate();await assert.rejects(g.mutate("x",async()=>{throw new Error("connection timeout");}),/ambiguous/);await assert.rejects(g.close(),/ambiguous/);});
test("DB publication proof accepts only exact empty Docker inspect representations",()=>{assert.match(host,/inspect --format '\{\{json \.HostConfig\.PortBindings\}\}' "\$pinned_db_id"/);assert.match(host,/case "\$port_bindings" in '\{\}'\|'null'\)/);assert.doesNotMatch(host,/compose port db/);const accepted=(value)=>value==="{}"||value==="null";for(const value of ["{}","null"])assert.equal(accepted(value),true);for(const value of ["",`{"3306/tcp":[{"HostIp":"0.0.0.0","HostPort":"3306"}]}`,`{"33060/tcp":[{"HostPort":"33060"}]}`,"[]","malformed","{} "])assert.equal(accepted(value),false);});
test("prepare checks all port bindings on the already validated exact DB ID",()=>{assert.match(host,/id=\$\(identity\); require_db_unpublished "\$id"; compose port app/);assert.match(host,/DB port-binding inspection failed/);assert.match(host,/published ports or malformed/);});
test("backup and resume bind exact path hash and run ID",()=>{assert.match(host,/sha256sum "\$backup"/);assert.match(host,/backup hash mismatch/);assert.match(host,/unknown run ID/);assert.doesNotMatch(host,/latest|\*\.sql/);});
test("restore retains exact existing destructive acknowledgement",()=>{assert.match(host,/DESTROY-MODERN-FIELD-TEST-V1-DATA/);assert.match(host,/"\$directory\/field-test" restore "\$backup"/);});
function deltaSnapshots(extraTable) { const tables={};for(const table of Object.keys(snap.contract))tables[table]={rowCount:"0",digest:"same"};const recoveryPoint={aggregateDigest:"a".repeat(64),tables},postDelta={aggregateDigest:"b".repeat(64),tables:structuredClone(tables)};for(const table of EXPECTED_POST_BACKUP_TABLES)postDelta.tables[table]={rowCount:"1",digest:`changed-${table}`};if(extraTable)postDelta.tables[extraTable]={rowCount:"1",digest:"undeclared"};return {recoveryPoint,postDelta}; }
test("computed delta ledger accounts for exact observed tables and completed outcomes",()=>{const {recoveryPoint,postDelta}=deltaSnapshots(),ledger=buildDeltaLedger(recoveryPoint,postDelta,[{operationId:"mutation-1",outcome:"completed"}],["post:fact"]);assert.deepEqual(ledger.changedTables.map(x=>x.table),EXPECTED_POST_BACKUP_TABLES);assert.equal(classify({recoveryPoint,recovered:structuredClone(recoveryPoint),deltaLedger:ledger}).classification,"expected RPO loss");});
test("undeclared snapshot changes and ambiguous outcomes are corruption blockers",()=>{let pair=deltaSnapshots("players");assert.throws(()=>buildDeltaLedger(pair.recoveryPoint,pair.postDelta,[{outcome:"completed"}],["fact"]),/differ/);pair=deltaSnapshots();assert.throws(()=>buildDeltaLedger(pair.recoveryPoint,pair.postDelta,[{outcome:"ambiguous"}],["fact"]),/unambiguous/);const ledger=buildDeltaLedger(pair.recoveryPoint,pair.postDelta,[{outcome:"completed"}],["fact"]);assert.equal(classify({recoveryPoint:pair.recoveryPoint,recovered:{...pair.recoveryPoint,aggregateDigest:"c".repeat(64)},deltaLedger:ledger}).classification,"corruption");});
test("runner has explicit resume gate and no automatic reset",()=>{assert.match(runner,/phase===\"resume\"/);assert.match(runner,/assertPristineBootstrap\(bootstrap, baseline\)/);assert.doesNotMatch(runner,/field-test reset|data-operation\.js reset/);});
test("rehearsal uses container Node, no Docker socket mount, and no legacy target",()=>{assert.match(host,/app_node/);assert.doesNotMatch(host,/(^|[;&])\s*node rehearsal/m);const compose=fs.readFileSync(path.join(root,"deploy/field-test/compose.yaml"),"utf8");assert.doesNotMatch(compose,/docker\.sock/);assert.doesNotMatch(host,/Legacy|production|rehearsal-db/);});
test("controlled single-writer claim wording is exact",()=>{assert.match(runner,/Recovery point bound to backup under the controlled single-writer synthetic rehearsal assumption\./);assert.match(runner,/CONTROLLED-SINGLE-WRITER-MODERN-FIELD-TEST-V1/);});
function pristineProjection(overrides={}) { return { tournament:{id:1,name:"赛事活动",sport:"pickleball",status:"draft"},players:[],matches:[],pairings:[],mode:"round-robin",...overrides }; }
function pristineSnapshot(nonempty) { const tables={};for(const table of Object.keys(snap.contract))tables[table]={rowCount:table==="tournaments"?"1":"0"};if(nonempty)tables[nonempty]={rowCount:"1"};return {tables}; }
test("canonical post-reset bootstrap tournament is accepted",()=>{assert.equal(assertPristineBootstrap(pristineProjection(),pristineSnapshot()),true);});
test("real existing competition state is rejected",()=>{assert.throws(()=>assertPristineBootstrap(pristineProjection({tournament:{id:1,name:"Real Event",sport:"pickleball",status:"running"},matches:[{id:1}]}),pristineSnapshot("matches")));});
test("non-pristine draft bootstrap lookalikes are rejected",()=>{for(const projection of [pristineProjection({players:[{id:1}]}),pristineProjection({tournament:{id:1,name:"赛事活动",sport:"pickleball",status:"draft"},mode:"fixed-pair"})])assert.throws(()=>assertPristineBootstrap(projection,pristineSnapshot()));assert.throws(()=>assertPristineBootstrap(pristineProjection(),pristineSnapshot("competition_referees")));});
test("prepare validates and configures bootstrap through supported API without creating competition",()=>{const prepare=runner.slice(runner.indexOf("async function prepare()"),runner.indexOf("async function bindDelta()"));assert.match(prepare,/assertPristineBootstrap\(bootstrap, baseline\)/);assert.match(prepare,/mutation\(gate,"configure-bootstrap","PUT","\/api\/competition\/1"/);assert.doesNotMatch(prepare,/"POST","\/api\/competition"/);});
test("bindDelta records a new OPEN process epoch before post-backup mutation",()=>{const bind=runner.slice(runner.indexOf("async function bindDelta()"),runner.indexOf("async function recordHost()"));assert.doesNotMatch(bind,/gate\.open\(/);const equality=bind.indexOf("assert.deepEqual(b,evidence.recoveryPoint"),opened=bind.indexOf("gateOpenedAt="),persisted=bind.indexOf("atomic(manifestPath,evidence)"),mutation=bind.indexOf("await accept(gate");assert.ok(equality>=0&&equality<opened);assert.ok(opened<persisted&&persisted<mutation);assert.match(bind,/reopenedAsNewProcessMutationEpoch=true/);assert.match(bind,/phase="post-backup-delta-in-progress"/);});
test("paused verify is bounded inside the selected Docker privilege boundary",()=>{assert.doesNotMatch(host,/timeout 5 "\$directory\/field-test" verify/);assert.match(host,/timeout --foreground --signal=KILL 5 docker exec "\$pinned_app_id" node deploy\/field-test\/data-operation\.js verify/);assert.match(host,/sudo -n timeout --foreground --signal=KILL 5 docker exec "\$pinned_app_id"/);assert.match(host,/app_id=\$\(app_identity\)/);assert.match(host,/require_verify_exec_gone "\$app_id"/);assert.match(host,/processes=\$\(docker_command top "\$pinned_app_id" -eo args\) \|\| die "cannot inspect/);const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"sudo-timeout-"));fs.writeFileSync(path.join(tmp,"sudo"),'#!/bin/sh\n[ "$1" = -n ] && shift\nexec "$@"\n',{mode:0o755});fs.writeFileSync(path.join(tmp,"docker"),'#!/bin/sh\nexec sleep 30\n',{mode:0o755});const started=Date.now(),result=cp.spawnSync(path.join(tmp,"sudo"),["-n","timeout","--foreground","--signal=KILL","1",path.join(tmp,"docker"),"exec","a".repeat(64),"node","deploy/field-test/data-operation.js","verify"],{encoding:"utf8"});assert.notEqual(result.status,0);assert.ok(Date.now()-started<4000,"sudo-owned timeout did not return within its hard bound");});
test("post-timeout app process inspection fails closed",()=>{const check=host.slice(host.indexOf("require_verify_exec_gone()"),host.indexOf("health()"));assert.match(check,/docker_command top/);assert.match(check,/\|\| die "cannot inspect bounded verify app exec processes"/);assert.match(check,/bounded verify left a live app exec process/);assert.doesNotMatch(check,/docker_command top[^\n]*\| grep/);});
test("paused DB probe uses a prevalidated authenticated DB-backed request",()=>{const start=host.indexOf("probe_cookie=$(app_node"),pre=host.indexOf("authenticated DB-backed read failed before pause"),pause=host.indexOf('docker_command pause "$id"'),during=host.indexOf('Cookie: $probe_cookie',host.indexOf("verify_failed=false"));assert.ok(start>=0&&start<pre&&pre<pause&&pause<during);assert.match(host,/probe-cookie/);assert.match(runner,/authenticatedDbReadSucceededBeforePause:observed\("FAILURE_AUTH_READ_BEFORE"\)/);assert.doesNotMatch(host,/curl -fsS --max-time 3 "http:\/\/127\.0\.0\.1:\$port\/api\/competition/);});
function phaseOneEvidence(overrides={}) { const id="a".repeat(64);return {run:{phase:"restore-gate"},postBackupDelta:{allObservedDifferencesAccountedFor:true},databaseIdentity:{containerId:id},environment:{dockerAccessMode:"direct"},failureObserved:{pausedExactId:true,verifyFailedOrTimedOut:true,authenticatedDbReadSucceededBeforePause:true,dbBackedReadFailedOrTimedOut:true,writesIssued:false,postDeltaReverifiedAfterUnpause:true},watchdog:{armed:true,explicitUnpauseHealthy:true,normalPathDisarmed:true,containerId:id,dockerAccessMode:"direct"},...overrides};}
test("restore gate before failure observation is rejected",()=>{assert.throws(()=>assertRestoreGateEvidence(phaseOneEvidence({failureObserved:null})),/missing/);});
test("failure observation without completed watchdog recovery is rejected",()=>{const evidence=phaseOneEvidence();evidence.watchdog.normalPathDisarmed=false;assert.throws(()=>assertRestoreGateEvidence(evidence));});
test("aborted injection is non-resumable and complete Phase 1 is resumable",()=>{assert.throws(()=>assertRestoreGateEvidence(phaseOneEvidence({run:{phase:"post-backup-delta-complete"}})),/Phase 1/);assert.equal(assertRestoreGateEvidence(phaseOneEvidence()),true);});
test("restore gate is persisted only after unpause, disarm, and post-delta revalidation",()=>{const complete=runner.slice(runner.indexOf("async function completeFailureProof()"),runner.indexOf("async function resume()"));const snapshot=complete.indexOf("assert.deepEqual(await dbSnapshot()"),gate=complete.indexOf('e.run.phase="restore-gate"'),persist=complete.lastIndexOf("atomic(manifestPath,e)");assert.ok(snapshot>=0&&snapshot<gate&&gate<persist);const hostDisarm=host.indexOf("disarm; compose exec"),completeCall=host.indexOf("complete-failure-proof");assert.ok(hostDisarm>=0&&hostDisarm<completeCall);});
test("runner cannot mark PASS before host final verify",()=>{const resumeRunner=runner.slice(runner.indexOf("async function resume()"),runner.indexOf("(async()=>"));assert.doesNotMatch(resumeRunner,/summary=\{passed:true/);assert.match(resumeRunner,/summary=\{passed:false,awaitingFinalIntegrity:true/);const completion=runner.slice(runner.indexOf("function completeFinalIntegrity()"),runner.indexOf("async function resume()"));assert.match(completion,/existingVerifyPassed:true/);assert.match(completion,/summary=\{passed:true/);const resumeHost=host.slice(host.indexOf(" resume)"),host.indexOf(" watchdog-proof-start)"));assert.ok(resumeHost.indexOf('field-test" verify')<resumeHost.indexOf("complete-final-integrity"));});
test("destructive resume checks phase and exact DB identity before restore",()=>{const resume=host.slice(host.indexOf(" resume)"),host.indexOf(" watchdog-proof-start)")),phase=resume.indexOf("assert-restore-gate"),identity=resume.indexOf("assert-db-identity"),restore=resume.indexOf('field-test" restore');assert.ok(phase>=0&&phase<identity&&identity<restore);assert.match(phaseOneSource,/allObservedDifferencesAccountedFor/);});
test("recovery evidence records artifact identity and enforces distinct run directories",()=>{assert.match(runner,/artifactIdentity:{buildId:readRuntimeBuildId\(\),source:BUILD_ID_FILE}/);assert.match(runner,/!fs\.existsSync\(dir\)/);assert.match(fieldTest,/chown -R node:node \/app\/rehearsal\/evidence\/db-recovery/);});
test("failed backup binding cannot admit post-backup mutations",()=>{const bind=runner.slice(runner.indexOf("async function bindDelta()"),runner.indexOf("async function recordHost()"));assert.ok(bind.indexOf("assert.deepEqual(b,evidence.recoveryPoint")<bind.indexOf("new MutationGate()"));assert.match(host,/assert-restore-gate/);assert.match(phaseOneSource,/run has not completed the Phase 1 failure proof/);});
test("prepare routes every mutation through its single declared gate",()=>{const prepare=runner.slice(runner.indexOf("async function prepare()"),runner.indexOf("async function bindDelta()"));assert.equal((prepare.match(/new MutationGate\(\)/g)||[]).length,1);assert.doesNotMatch(prepare,/\b(?:mutation|dispatch|accept|start|finish)\(g,/);for(const operation of ["mutation","dispatch","accept","start","finish"])assert.match(prepare,new RegExp(`\\b${operation}\\(gate,`));});
test("scenario reserves all five approved roles and scores",()=>{for(const x of ["rpA","rpB","rpC","deltaD","contE"])assert.ok(runner.includes(x));for(const x of [",7,\"pre\"",",8,\"post\"",",9,\"continue\"",",6,\"continue\""])assert.ok(runner.includes(x));});
test("dedicated evidence schema contains all required sections",()=>{const schema=require("../deploy/field-test/evidence/db-recovery-manifest.schema.json");for(const x of ["run","environment","artifactIdentity","databaseIdentity","recoveryPoint","recoveryPointBinding","backupIdentity","postBackupDelta","failureObserved","watchdog","restoreCompleted","recoveredState","expectedRpoLoss","operationalContinuation","finalIntegrity","legacyBoundary","summary"])assert.ok(schema.required.includes(x));});
test("host-shell JSON stability proof preserves the Lighthouse execution boundary",()=>{assert.match(fieldTest,/db-recovery-json-stability-proof/);assert.doesNotMatch(jsonProof,/\bnode\b|docker\.sock|Legacy|eval|docker prune|docker network|docker volume/);assert.match(jsonProof,/image=mysql:8\.4/);assert.match(jsonProof,/docker_command rm --force "\$container_id"/);assert.doesNotMatch(jsonProof,/rm --force [^"\n]*\*/);assert.match(jsonProof,/docker info/);assert.match(jsonProof,/sudo -n -k docker info/);assert.match(jsonProof,/sudo -n docker "\$@"/);assert.match(jsonProof,/server is not MySQL 8\.4/);assert.match(jsonProof,/server is not Oracle MySQL/);});
test("host-shell JSON stability proof uses backup flags and complete server-side matrix",()=>{for(const flag of ["--single-transaction","--routines","--triggers","--no-tablespaces","--set-gtid-purged=OFF","--default-character-set=utf8mb4"])assert.ok(jsonProof.includes(flag),flag);for(const value of ["multi-key-object","nested-object","array","numeric-values","booleans","strings","json-null"])assert.ok(jsonProof.includes(value),value);assert.match(jsonProof,/HEX\(CAST\(payload AS BINARY\)\)/);assert.match(jsonProof,/cmp "\$temporary_directory\/before\.tsv" "\$temporary_directory\/after\.tsv"/);});
test("MySQL 8.4 JSON byte stability harness covers the required value matrix",()=>{assert.deepEqual(VALUES.map(x=>x.label),["multi-key-object","nested-object","array","numeric-values","booleans","strings","json-null"]);});
test("MySQL 8.4 JSON byte stability integration",{skip:process.env.TOP_MYSQL_84_JSON_STABILITY!=="1"?"opt in with TOP_MYSQL_84_JSON_STABILITY=1; requires Docker and mysql:8.4":false,timeout:180000},async()=>{const evidence=await proveMysql84JsonDumpRestoreStability();assert.equal(evidence.exactMatch,true);assert.match(evidence.version,/^8\.4/);});
